# Nextnet (S)
# protocol_hash: TBA

node_config_network:
  activation_account_name: teztnetsbaker
  chain_name: TEZOS_NEXTNET_2025-06-10T12:10:00Z
  genesis:
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2025-06-10T12:10:00Z"
  dal_config:
    activated: true

activation:
  protocol_hash: PsRiotumaAMotcRoDWW1bysEhQy2n1M5fy8JgRp8jjRfHGmfeA7
  protocol_parameters:
    aggregate_attestation: false
    allow_tz4_delegate_enable: false
    all_bakers_attest_activation_level: null
    consensus_rights_delay: 2
    blocks_preservation_cycles: 1
    delegate_parameters_activation_delay: 3
    blocks_per_cycle: 300
    blocks_per_commitment: 25
    nonce_revelation_threshold: 50
    cycles_per_voting_period: 1
    hard_gas_limit_per_operation: "1040000"
    hard_gas_limit_per_block: "1386666"
    proof_of_work_threshold: "-1"
    minimal_stake: "6000000000"
    minimal_frozen_stake: "600000000"
    vdf_difficulty: "10000000"
    origination_size: 257
    issuance_weights:
      base_total_issued_per_minute: "85007812"
      baking_reward_fixed_portion_weight: 5120
      baking_reward_bonus_weight: 5120
      attesting_reward_weight: 10240
      dal_rewards_weight: 2275
      seed_nonce_revelation_tip_weight: 1
      vdf_revelation_tip_weight: 1
    cost_per_byte: "250"
    hard_storage_limit_per_operation: "60000"
    quorum_min: 2000
    quorum_max: 7000
    min_proposal_quorum: 500
    liquidity_baking_subsidy: "5000000"
    liquidity_baking_toggle_ema_threshold: 100000
    max_operations_time_to_live: 150
    minimal_block_delay: "4"
    delay_increment_per_round: "2"
    consensus_committee_size: 7000
    consensus_threshold_size: 4667
    minimal_participation_ratio:
      numerator: 2
      denominator: 3
    limit_of_delegation_over_baking: 9
    percentage_of_frozen_deposits_slashed_per_double_baking: 500
    max_slashing_per_block: 10000
    max_slashing_threshold: 
      numerator: 1
      denominator: 3
    cache_script_size: 100000000
    cache_stake_distribution_cycles: 5
    cache_sampler_state_cycles: 5
    dal_parametric:
      feature_enable: true
      incentives_enable: false
      number_of_slots: 32
      attestation_lag: 8
      attestation_threshold: 66
      redundancy_factor: 8
      page_size: 3967
      slot_size: 126944
      number_of_shards: 512
      minimal_participation_ratio:
        numerator: "16"
        denominator: "25"
      rewards_ratio:
        numerator: "1"
        denominator: "10"
      traps_fraction:
        numerator: "1"
        denominator: "2000"
    smart_rollup_arith_pvm_enable: true
    smart_rollup_origination_size: 6314
    smart_rollup_challenge_window_in_blocks: 62
    smart_rollup_stake_amount: "32000000"
    smart_rollup_commitment_period_in_blocks: 31
    smart_rollup_max_lookahead_in_blocks: 46875
    smart_rollup_max_active_outbox_levels: 31500
    smart_rollup_max_outbox_messages_per_level: 100
    smart_rollup_number_of_sections_in_dissection: 32
    smart_rollup_timeout_period_in_blocks: 781
    smart_rollup_max_number_of_cemented_commitments: 5
    smart_rollup_max_number_of_parallel_games: 32
    smart_rollup_reveal_activation_level:
      raw_data:
        Blake2B: 0
      metadata: 0
      dal_page: 1
      dal_parameters: 1
      dal_attested_slots_validity_lag: 241920
    smart_rollup_private_enable: true
    smart_rollup_riscv_pvm_enable: true
    tolerated_inactivity_period: 2
    zk_rollup_enable: true
    zk_rollup_origination_size: 4000
    zk_rollup_min_pending_to_process: 10
    zk_rollup_max_ticket_payload_size: 2048
    global_limit_of_staking_over_baking: 9
    edge_of_staking_over_delegation: 3
    adaptive_rewards_params:
      issuance_ratio_final_min:
        numerator: "1"
        denominator: "400"
      issuance_ratio_final_max:
        numerator: "1"
        denominator: "10"
      issuance_ratio_initial_min:
        numerator: "9"
        denominator: "200"
      issuance_ratio_initial_max:
        numerator: "11"
        denominator: "200"
      initial_period: 10
      transition_period: 50
      max_bonus: "50000000000000"
      growth_rate:
        numerator: "1"
        denominator: "100"
      center_dz:
        numerator: "1"
        denominator: "2"
      radius_dz:
        numerator: "1"
        denominator: "50"
    direct_ticket_spending_enable: false
    testnet_dictator: tz1e1TX7KghsqWUBXWmBTAAtPK3W6JTbNc82

nodes:
  tezos-baking-node:
    env:
      all:
        TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"
    instances:
      - bake_using_accounts:
          - teztnetsbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
            max_active_rpc_connections: 1000
          metrics_addr: ["0.0.0.0:9932"]
        is_bootstrap_node: true
        identity:
          # hard-coded identity - saves 1-2 minutes on daily cron
          peer_id: idqnaeAw4oGfUEnKrLH2fZYRQo4Ev1
          public_key:
            c988f65dfbc50ef61d8db84b89ea8df93643328bbd0524321582e39d33e32115
          secret_key:
            38ffcb4629db7152141824835bebf42f12d90933d68773d78002f86637500b62
          proof_of_work_stamp: 3ee07208e41a0489299909c0bd3cac5c05b20a9acc4a3bc7
    runs:
      - octez_node
      - baker
      - accuser
      - vdf
    bootstrapped_readiness_probe: false
    storage_size: 250Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

bootstrap_peers:
  - nextnet.tzinit.org

dalNodes:
  dal-bootstrap:
    bootstrapProfile: true
    node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
    storageSize: 100Gi
    ingress:
    # ingress details filled up by pulumi
    identity:
      peer_id: "idtJh8bYedP2hKdRk6oCLX3SS2KuTM"
      public_key:
        "5a6cd66cbd2f69817fb2eb81e5dd2a9c4f88df950fc90a96a08fe3976724a063"
      secret_key:
          "42f716781cf80b2b7ad129ac56dfcb1b333f3021e49c6729199de8303c7152c9"
      proof_of_work_stamp: "b7edd6ea938998f8f088b83b692baeddb49f5522f07572f9"
  dal-dal1:
    attest_using_accounts:
      - teztnetsbaker
    attesterProfiles: tz1TnEtqDV9mZyts2pfMy6Jw1BTPs4LMjL8M
    node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
    storageSize: 100Gi
    ingress:
    # ingress details filled up by pulumi
    identity:
      peer_id: "ids8gZ6Gu67e58DqPn2e9VyjasB1jo"
      public_key:
        "c4ea1f6dddfa43b87b6a37432c4c34e1c79baeed5ff165fee2a85ffafb819e5f"
      secret_key:
          "a67519da6166f97ca2dea6dc519f1a453d96e01348816d102fb9a7099ee08137"
      proof_of_work_stamp: "c85a3aab8a1fc903e8c7e9bcd1714a890e22f160a96d9779"

dal_deploy_slot_injector:
  enabled: true
  inject_using_account: teztnetsbaker
  node_rpc_url: http://tezos-baking-node-0.tezos-baking-node:8732
  dal_node_rpc_url: http://dal-dal1:10732
  slot_size: 65536

full_snapshot_url: null
rolling_snapshot_url: null
rolling_tarball_url: null
archive_tarball_url: null
snapshot_source: null

images:
  octez: tezos/tezos:master_3f47ba6f_20250610075602

protocols:
  - command: PsRiotum
    vote:
      liquidity_baking_toggle_vote: "pass"
  - command: PtSEouLo
    vote:
      liquidity_baking_toggle_vote: "pass"
    
accounts:
  teztnetsbaker:
    # tz1TnEtqDV9mZyts2pfMy6Jw1BTPs4LMjL8M
    bootstrap_balance: "1500000000000"
    is_bootstrap_baker_account: true
    type: secret
    dal_node_rpc_url: http://dal-dal1:10732
  ecadlabs:
    # tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  ecadlabs_2:
    # tz1RuHDSj9P7mNNhfKxsyLGRDahTX5QD1DdP
    key: edpkthQu5xeKjD9Dxh5tAf3f61z2Nteqk9xRVPVoZekk1CF738zbcJ
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  captstake:
    # tz1N29q5T3jJ2i1JEWHax7q1NRkDMADj6fof 
    key: edpkvV1FvrCmd68k6yMCfhiW6WNXSb1kZPWJhkr9KZPTtW7ukBs8dj
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  german:
    #  tz1TGKSrZrBpND3PELJ43nVdyadoeiM1WMzb
    key: edpkvG8RpyhnPi3ugWWvavsKwR79rb7iMvedeFNxBdyCvenTDZeC9n
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  mathias:
    # tz1SrPwhZgr8MHcyPtGtFrKrtTAjzuiJpYsu
    key: edpkugFkkbDB4fx6u8KwcKM3KvZ9z465iaR38q4Q1sNgZejEh19gzv
    type: public
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  marco:
    # Marco Schurtenberger
    # Inference
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
    # TF production-style bakers
  tf1:
    # TF Testnet A
    # tz3Q67aMz7gSMiQRcW729sXSfuMtkyAHYfqc - ..., N, P, R, ...
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  tf2:
    # TF Testnet B
    # tz3Q1fwk1vh3zm5LqyUV9e2wZBdaEXcovh2r - ..., O, Q, S, ...
    key: p2pk66p7iVbEFyJaYM5bjJmXP74B7qso8rXMCmKwVRdRZunMdhUjYBH
    #
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  vincent:
    # XTZmaster
    # tz1XMiZwHpHZ8a1AfwRWKfzLskJgZNyV8PHs
    key: edpkvaZQ6tt9XgJJTonjFpzwaqDV7RWUQMT7TmntBJ5yXmDsPb8T7L
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  deligation_danilo:
    # Capt Stake's sidekick
    # tz1iir8f4JpoC1TuWq3tPN2E7LaMwxzNe9tS
    key: edpkubZwGk9EPfxGYA2y4axvr1WfUDkSQFvHd2cg68wcvwSf5Mua6H
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  dalman:
    key: edpkvKpSMUDaKZKCLwE69XDiijZcAuuFH2h2NcRiTQD4W3FLGAzxei
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false

  # NL Vigies Nodes (Corentin)
  # tz1ViGF3WbG8gZH6w2oizRjJkyi43BtGr1ma
  nl_vigies_full:
    key: edpkvBMSXw1VNAqQDBweScaDPFnkUidDpX3FUWuPe5wn6QHUKgGBWT
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  # tz1ViGA65hAiAvWonzuc4ndnUkztCnbDTsFj
  nl_vigies_archive:
    key: edpktjogMNJ34uG9ED3WZzP8eKiGs4zzJdhAPZ9B4rbfwn111zhHQS
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  # tz1VigrUuQDe1EikkGQTWGMS6JVkaKb1rnx1
  nl_vigies_rolling:
    key: edpkvQ9wHEWVtuHBk8qjjYJNETVV1UmUoiz9ME3PK3M7ehnZVSEhBQ
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  # tz1VigxFsaiceHojGNfEKMsPHuL8sxK4t7jZ
  nl_vigies_default:
    key: edpkvaKebJW8Y871pHq3sbNq8vre2Gyk9pxZ9mc3TTqYEP2LGWZhX9
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  # "Zir0h's Testnet bakery" 
  # tz1NNT9EERmcKekRq2vdv6e8TL3WQpY8AXSF
  zir0h:
    key: edpkvGTRQwdJ11QENyYifpnnNxthH6KzQsFtD5FKtEJj3MaijAUkof
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false  
  # tz1iHq8QLYf3CvPV23UVkhk6WG74psJ4WpWp (Barry Manilow)
  barry_manilow:
    key: edpkvKpSMUDaKZKCLwE69XDiijZcAuuFH2h2NcRiTQD4W3FLGAzxei
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false
  #  tz3PgFHdYvEGEbUo1pUJmuNH8fgc8cwARKfC

  # Albin
  poulet:
    key: p2pk67wXWykNWau9DpoAqGBuGdo7ke8TkF32D6PJt5QEx4P9b27MKbK
    bootstrap_balance: "1000000000000"
    is_bootstrap_baker_account: false  
   # tz4P1CLxknigJT5HF2RDGJxuzjiNLE3Gs2bf
   #  key: BLpk1rk1rAKPMtLDUbxoPmjyi9axuSQZUxdYArzeahFTP4Z4FNvboXxbvsAod8cecUmqrtnjfFdn


  # Faucets
  #
  marcofaucet:
    # Marco Schurtenberger
    # tz1bRUpEJ9zKLAe3zrE81DGDayH9S4P7ZqGz
    # Inference Faucet
    key: edpkuzzJcZDjXL7hWMnyC1y3joyrGgBiDVVRJUqnG3LKgPvZrpNWxT
    is_bootstrap_baker_account: false
    bootstrap_balance: "1000000000000"
  tzktfaucet:
    # Dmitry's personal fund
    # tz1KhnTgwoRRALBX6vRHRnydDGSBFsWtcJxc
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    bootstrap_balance: "200000000000000"
    is_bootstrap_baker_account: false
  faucet:
    # faucet on teztnets.xyz platform
    # tz1a4GT7THHaGDiTxgXoatDWcZfJ5j29z5RC
    key: edpkvGYHoY5kwq13Ak6r4fLa1GGSHKJZVe7xJFV6ZgHwdZeaHy3WZj
    bootstrap_balance: "200000000000000"
    is_bootstrap_baker_account: false
  # DAL Rich account and baker (Francois Thire)
  dal_rich_account:
    key: edpkuwL7MVYArfQN9jyR8pZTqmFGYFWTYhhF4F8KWjr2vB18ozTqbd
    bootstrap_balance: "370000000000"
    is_bootstrap_baker_account: false
  tfrichfund:
    # an account that would allow Chris to finally have that holiday
    # if only it were on mainnet...
    # tz1VRj54TQDtUGgv6gF4AbGbXMphyDpVkCpf
    key: edpkvWFRKD8soryXJkcHCr9shnxhkxJLGG5FJAHquka992bgf86YxC
    bootstrap_balance: "5000000000000000"
    is_bootstrap_baker_account: false
  tz1THUNA:
    # tz1THUNARo58aD5YdNGYPnWNnvd8yHPrMdsF
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000000"

