accounts:
  teztnetsbaker:
    # tz1TnEtqDV9mZyts2pfMy6Jw1BTPs4LMjL8M
    bootstrap_balance: "9700000000000"
    is_bootstrap_baker_account: true
    # key injected by pulumi
  tfrichfund:
    # an account that would allow Chris to retire if it was on mainnet
    # tz1VRj54TQDtUGgv6gF4AbGbXMphyDpVkCpf
    key: edpkvWFRKD8soryXJkcHCr9shnxhkxJLGG5FJAHquka992bgf86YxC
    bootstrap_balance: "50000000000000000"
    is_bootstrap_baker_account: false
  bakingbadfaucet:
    # baking bad maintains a telegram faucet bot
    # tz1KhnTgwoRRALBX6vRHRnydDGSBFsWtcJxc
    key: edpkuFRauFAdhipQu9s4xmfNJWmtLxPKpoaoG41gYGq5AgUA43Vxqx
    is_bootstrap_baker_account: false
    bootstrap_balance: "5000000000000000"
  tz1THUNA:
    # tz1THUNARo58aD5YdNGYPnWNnvd8yHPrMdsF
    # Romain's faucet
    key: edpkuh3WSwziyd6nXqDXeh48vZHp5ETxFd43EdkbzhmW98BvuLXK81
    is_bootstrap_baker_account: false
    bootstrap_balance: "50000000000000000"
  faucet:
    # the faucet on teztnets platform
    # tz1a4GT7THHaGDiTxgXoatDWcZfJ5j29z5RC
    key: edpkvGYHoY5kwq13Ak6r4fLa1GGSHKJZVe7xJFV6ZgHwdZeaHy3WZj
    is_bootstrap_baker_account: false
    bootstrap_balance: "15000000000000"
  mkbaker:
    # tz1PZY3tEWmXGasYeehXYqwXuw2Z3iZ6QDnA
    # Michael Kernaghan
    key: edpkvE16Jw7ijHkUyPLkBR5sm7p7XxRxd1eThX3S8RCQCuEJwqPYsR
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  german:
    # tz1TGKSrZrBpND3PELJ43nVdyadoeiM1WMzb
    # German
    key: edpkvG8RpyhnPi3ugWWvavsKwR79rb7iMvedeFNxBdyCvenTDZeC9n
    is_bootstrap_baker_account: false
    bootstrap_balance: "100000000000"
  raphcaud:
    # tz1V1Lu93CPgeN6AXM3Ba9oreAAxcJCoYNJN
    # Raphael C
    key: edpku9SHSvCK7jMkyJo3CMnBeMhB337uat9zoHiANvPzisjMthkzb8
    is_bootstrap_baker_account: true
    bootstrap_balance: "100000000000"
  tf:
    # TF production-style baker
    #
    # tz3Q67aMz7gSMiQRcW729sXSfuMtkyAHYfqc - ..., N, P, R, ...
    key: p2pk66gP3wq6k9QgNwAgaGLeXc3YFfrxgYdC7cdYuJWAHYBw4hExVHW
    #
    # tz3Q1fwk1vh3zm5LqyUV9e2wZBdaEXcovh2r - ..., O, Q, S, ...
    #key: p2pk66p7iVbEFyJaYM5bjJmXP74B7qso8rXMCmKwVRdRZunMdhUjYBH
    #
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  marco:
    # Marco Schurtenberger
    key: edpkubw32gvTfUYRERGECHbMTsiLdM9z9JrEXGVEahbZf9yMhTozSg
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  andrewk:
    # tz1aKiShiJWeeTSGzuvYWhZPqvMShgrz9Qy4
    key: edpkvSdrHag4FYzJMD3Zfr4s7xiLoX1MWWR7tQVFcs5Epvb9bnMTVQ
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs:
    # tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD
    key: edpkvP1NXoo8vhYbPSvXdy466EHoYWBpf6zmjghB2p3DwJPjbB5nsf
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  ecadlabs_2:
    # tz1RuHDSj9P7mNNhfKxsyLGRDahTX5QD1DdP
    key: edpkthQu5xeKjD9Dxh5tAf3f61z2Nteqk9xRVPVoZekk1CF738zbcJ
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  killian_d:
    # tz1gBnaS1n7LKqpaRnyBX5MSmamadXXfzNpt
    key: edpkv7AqKLxQXWa2tHcPbMnah1JbMUHohvmvgPS7nVaB7kdNnrg1XW
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  albin:
    # tz1YtB3Hn6oghVk96vkpZt6PHrfbyRY1ciL3
    key: edpkuc4NCkkmTyLogcU32b7sU363J2jggs19EyBzhmms6JmjQZxEJo
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  lthms:
    # tz1WgKdbf7wc58nYLSiYXehtoWv3Z4Bswkf2
    key: edpkvEtgKrQ3opAJvYsdYJQNqGZqNmnASCnKtLRsGRnEr8b61mQddG
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  vincent_xtzmaster:
    # tz1XMiZwHpHZ8a1AfwRWKfzLskJgZNyV8PHs
    key: edpkvaZQ6tt9XgJJTonjFpzwaqDV7RWUQMT7TmntBJ5yXmDsPb8T7L
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"
  leotreasure:
    # tz1YAVSJRXGxqu4DSPJKkJpbB4Dn3KgzER3F, Leo Treasure
    key: edpkuiSD4sXuWYbNVYEdznoafszfLAX3tvYwnxYwrNCxvCaWrNUtzF
    is_bootstrap_baker_account: true
    bootstrap_balance: "1000000000000"

node_config_network:
  activation_account_name: teztnetsbaker
  chain_name: TEZOS_PARISNET_2024-04-10T15:00:00Z
  genesis:
    protocol: Ps9mPmXaRzmzk35gbAYNCAw6UXdE2qoABTHbN2oEEc1qM7CwT9P
    timestamp: "2024-04-10T15:00:00Z"
  user_activated_upgrades:
    - level: 8192
      replacement_protocol: PtParisBQscdCm6Cfow6ndeU6wKJyA3aV1j4D3gQBQMsTQyJCrz

# Parisnet activated
# activation:
#    protocol_hash: ProxfordYmVfjWnRcgjWH36fW6PArwqykTFzotUxRs6gmTcZDuH
#    protocol_parameters:
#      adaptive_issuance_activation_vote_enable: false
#      adaptive_issuance_launch_ema_threshold: 100000000
#      adaptive_rewards_params:
#        issuance_ratio_min:
#           numerator: '1'
#           denominator: '2000'
#        issuance_ratio_max:
#           numerator: '1'
#           denominator: '20'
#        max_bonus: '50000000000000'
#        growth_rate:
#           numerator: '245760'
#           denominator: '6144000'
#        center_dz:
#           numerator: '1'
#           denominator: '2'
#        radius_dz:
#           numerator: '1'
#           denominator: '50'
#      autostaking_enable: true
#      blocks_per_cycle: 8192
#      blocks_per_commitment: 64
#      blocks_per_stake_snapshot: 512
#      cache_script_size: 100000000
#      cache_stake_distribution_cycles: 8
#      cache_sampler_state_cycles: 8
#      consensus_committee_size: 7000
#      consensus_threshold: 4667
#      cost_per_byte: '250'
#      cycles_per_voting_period: 1
#      dal_parametric:
#        feature_enable: false
#        number_of_slots: 256
#        number_of_shards: 2048
#        attestation_lag: 2
#        attestation_threshold: 50
#        slot_size: 1048576
#        redundancy_factor: 16
#        page_size: 4096
#        blocks_per_epoch: 8
#      delay_increment_per_round: '3'
#      edge_of_staking_over_delegation: 2
#      global_limit_of_staking_over_baking: 5
#      hard_gas_limit_per_operation: '1040000'
#      hard_gas_limit_per_block: '2600000'
#      hard_storage_limit_per_operation: '60000'
#      issuance_weights:
#        attesting_reward_weight: 10240
#        base_total_issued_per_minute: '85007812'
#        baking_reward_fixed_portion_weight: 5120
#        baking_reward_bonus_weight: 5120
#        liquidity_baking_subsidy_weight: 1280
#        seed_nonce_revelation_tip_weight: 1
#        vdf_revelation_tip_weight: 1
#      limit_of_delegation_over_baking: 9
#      liquidity_baking_toggle_ema_threshold: 1000000000
#      max_operations_time_to_live: 240
#      min_proposal_quorum: 500
#      minimal_block_delay: '8'
#      minimal_frozen_stake: '600000000'
#      minimal_participation_ratio:
#        numerator: 2
#        denominator: 3
#      minimal_stake: '6000000000'
#      nonce_revelation_threshold: 512
#      origination_size: 257
#      percentage_of_frozen_deposits_slashed_per_double_attestation: 50
#      percentage_of_frozen_deposits_slashed_per_double_baking: 5
#      preserved_cycles: 5
#      proof_of_work_threshold: '-1'
#      quorum_max: 7000
#      quorum_min: 2000
#      smart_rollup_arith_pvm_enable: false
#      smart_rollup_challenge_window_in_blocks: 40
#      smart_rollup_commitment_period_in_blocks: 20
#      smart_rollup_max_lookahead_in_blocks: 30000
#      smart_rollup_max_active_outbox_levels: 20160
#      smart_rollup_max_number_of_cemented_commitments: 5
#      smart_rollup_max_number_of_parallel_games: 32
#      smart_rollup_max_outbox_messages_per_level: 100
#      smart_rollup_number_of_sections_in_dissection: 32
#      smart_rollup_origination_size: 6314
#      smart_rollup_private_enable: true
#      smart_rollup_reveal_activation_level:
#        raw_data:
#          Blake2B: 0
#        metadata: 0
#        dal_page: 2147483646
#        dal_parameters: 2147483646
#      smart_rollup_riscv_pvm_enable: false
#      smart_rollup_stake_amount: '10000000000'
#      smart_rollup_timeout_period_in_blocks: 500
#      testnet_dictator: tz1Xf8zdT3DbAX9cHw3c3CXh79rc4nK4gCe8
#      vdf_difficulty: '10000000000'
#      zk_rollup_enable: false
#      zk_rollup_origination_size: 4000
#      zk_rollup_max_ticket_payload_size: 2048
#      zk_rollup_min_pending_to_process: 10

nodes:
  tezos-baking-node:
    env:
      all:
        TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"
    instances:
      - bake_using_accounts:
          - teztnetsbaker
        config:
          shell:
            history_mode: archive
          rpc:
            cors-headers: [ "content-type" ]
            cors-origin: [ "*" ]
        is_bootstrap_node: true
    runs:
      - octez_node
      - baker
      - accuser
      - vdf
    storage_size: 200Gi
  # Overwrite default values.yaml rolling-node
  rolling-node: null

full_snapshot_url: null
rolling_snapshot_url: null
#full_snapshot_url: https://snapshots.eu.tzinit.org/parisnet/full
#rolling_snapshot_url: https://snapshots.eu.tzinit.org/parisnet/rolling
rolling_tarball_url: null
archive_tarball_url: null
snapshot_source: https://snapshots.tezos.marigold.dev/api/tezos-snapshots.json
snapshot_metadata_network_name: parisnet

images:
  octez: tezos/tezos:octez-v20.0-rc1

protocols:
  - command: Proxford
    vote:
      liquidity_baking_toggle_vote: "pass"
      adaptive_issuance_vote: "on"
  - command: PtParisB
    vote:
      liquidity_baking_toggle_vote: "pass"
      adaptive_issuance_vote: "on"

bootstrap_peers: 
  - parisnet.tzinit.org
